export const productList = [
  {
    id: 'p1',
    title: 'product 1',
    price: 210,
    colors: ['black', 'blue', 'gray', 'red'],
    imagesUrl: [
      'http://localhost:4000/api/media?design=001&type=tshirt&color=black',
      'http://localhost:4000/api/media?design=001&type=tshirt&color=blue',
      'http://localhost:4000/api/media?design=001&type=tshirt&color=gray',
      'http://localhost:4000/api/media?design=001&type=tshirt&color=red',
    ],
  },
  {
    id: 'p2',
    title: 'product 2',
    discount: 170,
    price: 220,
    colors: ['black', 'blue', 'gray', 'red'],
    imagesUrl: [
      'http://localhost:4000/api/media?design=002&type=tshirt&color=black',
      'http://localhost:4000/api/media?design=002&type=tshirt&color=blue',
      'http://localhost:4000/api/media?design=002&type=tshirt&color=gray',
      'http://localhost:4000/api/media?design=002&type=tshirt&color=red',
    ],
  },
  {
    id: 'p3',
    title: 'product 3',
    discount: 160,
    price: 205,
    colors: ['black', 'blue', 'gray', 'red'],
    imagesUrl: [
      'http://localhost:4000/api/media?design=003&type=tshirt&color=black',
      'http://localhost:4000/api/media?design=003&type=tshirt&color=blue',
      'http://localhost:4000/api/media?design=003&type=tshirt&color=gray',
      'http://localhost:4000/api/media?design=003&type=tshirt&color=red',
    ],
  },
  {
    id: 'p4',
    title: 'product 4',
    discount: 160,
    price: 205,
    colors: ['black', 'blue', 'gray', 'red'],
    imagesUrl: [
      'http://localhost:4000/api/media?design=004&type=tshirt&color=black',
      'http://localhost:4000/api/media?design=004&type=tshirt&color=blue',
      'http://localhost:4000/api/media?design=004&type=tshirt&color=gray',
      'http://localhost:4000/api/media?design=004&type=tshirt&color=red',
    ],
  },
  {
    id: 'p005',
    title: 'product 5',
    discount: 190,
    price: 205,
    colors: ['black', 'blue', 'gray', 'red'],
    imagesUrl: [
      'http://localhost:4000/api/media?design=005&type=tshirt&color=black',
      'http://localhost:4000/api/media?design=005&type=tshirt&color=blue',
      'http://localhost:4000/api/media?design=005&type=tshirt&color=gray',
      'http://localhost:4000/api/media?design=005&type=tshirt&color=red',
    ],
  },
  {
    id: 'p006',
    title: 'product 6',
    discount: 190,
    price: 220,
    colors: ['black', 'blue', 'gray', 'red'],
    imagesUrl: [
      'http://localhost:4000/api/media?design=006&type=tshirt&color=black',
      'http://localhost:4000/api/media?design=006&type=tshirt&color=blue',
      'http://localhost:4000/api/media?design=006&type=tshirt&color=gray',
      'http://localhost:4000/api/media?design=006&type=tshirt&color=red',
    ],
  },
  {
    id: 'p007',
    title: 'product 7',
    discount: 190,
    price: 205,
    colors: ['black', 'blue', 'gray', 'red'],
    imagesUrl: [
      'http://localhost:4000/api/media?design=007&type=tshirt&color=black',
      'http://localhost:4000/api/media?design=007&type=tshirt&color=blue',
      'http://localhost:4000/api/media?design=007&type=tshirt&color=gray',
      'http://localhost:4000/api/media?design=007&type=tshirt&color=red',
    ],
  },
  {
    id: 'p008',
    title: 'product 8',
    discount: 160,
    price: 215,
    colors: ['black', 'blue', 'gray', 'red'],
    imagesUrl: [
      'http://localhost:4000/api/media?design=008&type=tshirt&color=black',
      'http://localhost:4000/api/media?design=008&type=tshirt&color=blue',
      'http://localhost:4000/api/media?design=008&type=tshirt&color=gray',
      'http://localhost:4000/api/media?design=008&type=tshirt&color=red',
    ],
  },
  {
    id: 'p009',
    title: 'product 9',
    discount: 180,
    price: 205,
    colors: ['black', 'blue', 'gray', 'red'],
    imagesUrl: [
      'http://localhost:4000/api/media?design=009&type=tshirt&color=black',
      'http://localhost:4000/api/media?design=009&type=tshirt&color=blue',
      'http://localhost:4000/api/media?design=009&type=tshirt&color=gray',
      'http://localhost:4000/api/media?design=009&type=tshirt&color=red',
    ],
  },
  {
    id: 'p010',
    title: 'product 10',
    discount: 190,
    price: 205,
    colors: ['black', 'blue', 'gray', 'red'],
    imagesUrl: [
      'http://localhost:4000/api/media?design=010&type=tshirt&color=black',
      'http://localhost:4000/api/media?design=010&type=tshirt&color=blue',
      'http://localhost:4000/api/media?design=010&type=tshirt&color=gray',
      'http://localhost:4000/api/media?design=010&type=tshirt&color=red',
    ],
  },
  {
    id: 'p011',
    title: 'product 11',
    discount: 190,
    price: 225,
    colors: ['black', 'blue', 'gray', 'red'],
    imagesUrl: [
      'http://localhost:4000/api/media?design=011&type=tshirt&color=black',
      'http://localhost:4000/api/media?design=011&type=tshirt&color=blue',
      'http://localhost:4000/api/media?design=011&type=tshirt&color=gray',
      'http://localhost:4000/api/media?design=011&type=tshirt&color=red',
    ],
  },
  {
    id: 'p012',
    title: 'product 12',
    discount: 170,
    price: 225,
    colors: ['black', 'blue', 'gray', 'red'],
    imagesUrl: [
      'http://localhost:4000/api/media?design=012&type=tshirt&color=black',
      'http://localhost:4000/api/media?design=012&type=tshirt&color=blue',
      'http://localhost:4000/api/media?design=012&type=tshirt&color=gray',
      'http://localhost:4000/api/media?design=012&type=tshirt&color=red',
    ],
  },
  {
    id: 'p013',
    title: 'product 13',
    discount: 160,
    price: 205,
    colors: ['black', 'blue', 'gray', 'red'],
    imagesUrl: [
      'http://localhost:4000/api/media?design=013&type=tshirt&color=black',
      'http://localhost:4000/api/media?design=013&type=tshirt&color=blue',
      'http://localhost:4000/api/media?design=013&type=tshirt&color=gray',
      'http://localhost:4000/api/media?design=013&type=tshirt&color=red',
    ],
  },
];
